### PR TITLE
promote to prod

### PR DESCRIPTION
**Pull request by mendesfabio**
# Description

- #524 

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- `latestFXPrice` for every FX pool tokens
  - [x] [Avalanche](https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-avalanche-v2-beta/graphql?query=%7B%0A%09pools(%0A++++where:+%7B%0A++++++poolType:+%22FX%22%0A++++%7D%0A++)+%7B%0A++++tokens+%7B%0A++++++token+%7B%0A++++++++symbol%0A++++++++latestFXPrice%0A++++++++fxOracleDecimals%0A++++++%7D%0A++++%7D%0A%09%7D%0A%7D)
  - [x] [Polygon](https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-polygon-v2-beta/graphql?query=%7B%0A%09pools(%0A++++where:+%7B%0A++++++poolType:+%22FX%22%0A++++%7D%0A++)+%7B%0A++++tokens+%7B%0A++++++token+%7B%0A++++++++symbol%0A++++++++latestFXPrice%0A++++++++fxOracleDecimals%0A++++++%7D%0A++++%7D%0A%09%7D%0A%7D)

### `dev` -> `master`
- [x] I have [checked](https://balancer.github.io/balancer-subgraph-v2/status.html) that all beta deployments have synced
- [x] I have [checked](https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-polygon-prune-v2-beta/graphql?query=%0A%7B%0A++balancers%28block%3A%7Bnumber%3A1%7D%29%7B%0A++++id%0A++%7D%0A%7D) that the earliest block in the polygon pruned deployment is [49556211, Nov-05-2023 02:23:24](https://polygonscan.com/block/49556211)
  - [x] The earliest block is more than 24 hours old
- [x] I have checked that core metrics are the same in the beta and production deployments

### CODE REVIEW

**Comment by schystz** [comment]
Hmm if I check https://thegraph.com/hosted-service/subgraph/balancer-labs/balancer-avalanche-v2 and https://thegraph.com/hosted-service/subgraph/balancer-labs/balancer-polygon-v2, it says last updated date was still 22 days ago. It doesn't look like it has finished syncing yet, and I don't see the changes that #524 should have fixed.

Can we check if the pending version is still syncing at your end @mendesfabio?

**Comment by mendesfabio** [comment]
@schystz those are not the links of beta subgraphs - I'm sorry I just realized the links for tests were wrong. Please verify below:

- `latestFXPrice` for every FX pool tokens
  - [ ] [Avalanche](https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-avalanche-v2-beta/graphql?query=%7B%0A%09pools(%0A++++where:+%7B%0A++++++poolType:+%22FX%22%0A++++%7D%0A++)+%7B%0A++++tokens+%7B%0A++++++token+%7B%0A++++++++symbol%0A++++++++latestFXPrice%0A++++++++fxOracleDecimals%0A++++++%7D%0A++++%7D%0A%09%7D%0A%7D)
  - [ ] [Polygon](https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-polygon-v2-beta/graphql?query=%7B%0A%09pools(%0A++++where:+%7B%0A++++++poolType:+%22FX%22%0A++++%7D%0A++)+%7B%0A++++tokens+%7B%0A++++++token+%7B%0A++++++++symbol%0A++++++++latestFXPrice%0A++++++++fxOracleDecimals%0A++++++%7D%0A++++%7D%0A%09%7D%0A%7D)

**Comment by schystz** [comment]
Hi @mendesfabio , this looks good to me aside from the VCHF on avalanche. I realized we supplied an incorrect aggregator address of `0xA418573AB5226711c8564Eeb449c3618ABFaf677` instead of `0x3d22b2c729a952402d898d1041f5e4828ff3695c`. Can we pls merge this and I'll fix that on a separate PR (#527)?

**Comment by mendesfabio** [comment]
sure! @markusbkoch can you approve and merge this one?

**Review by markusbkoch — APPROVED** [review]

**Pull request merged**
