### PR TITLE
Adds descriptions to schema

### PR DESCRIPTION
**Pull request by PaulieB14**
@mendesfabio @markusbkoch Added descriptions to schema.  Once completed this will help finalize PR - Revised Subgraph Documents

### CODE REVIEW

**Comment by markusbkoch** [comment]
Thanks @PaulieB14 . The pattern Fabio linked to helps explorers like thegraph's playground display the documentation in their UI - see eg https://thegraph.com/hosted-service/subgraph/balancer-labs/balancer-gauges
image

**Comment by PaulieB14** [comment]
@mendesfabio @markusbkoch Thanks - makes sense. I used the # only because a few were already listed this way but probably should have used " ".  Wasn't fun but I got it done. lol.  Let me know if this is all good or needs revisions.  Thanks for working w/ me on it

**Comment by PaulieB14** [comment]
@mendesfabio @markusbkoch please let me know if I can do anything to help get this PR completed

**Comment by PaulieB14** [comment]
@mendesfabio @markusbkoch Any way this or https://github.com/balancer-labs/docs-developers/pull/5 would be looked at?  Please let me know if you need anything to complete.

**Pull request closed without merging**
